import { useState } from 'react';
import type { FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, CheckCircle2, MessageCircle } from 'lucide-react';
import { submitConsultation } from '@/services/educationClient';

export default function ConsultationPage() {
  const [submitted, setSubmitted] = useState(false); const [error, setError] = useState('');
  async function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const form = new FormData(event.currentTarget); try { await submitConsultation({ contactName: form.get('contactName'), contactPhone: form.get('contactPhone'), contactEmail: form.get('contactEmail'), goal: form.get('goal'), dietaryRestrictions: form.get('dietaryRestrictions'), preferredContactTime: form.get('preferredContactTime'), consent: form.get('consent') === 'on' }); setSubmitted(true); event.currentTarget.reset(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'تعذر إرسال الطلب'); } }
  return <main dir="rtl" className="min-h-screen bg-emerald-50/70 px-4 py-8"><section className="mx-auto max-w-3xl rounded-3xl bg-white p-6 shadow-xl md:p-10"><Link to="/education" className="inline-flex items-center gap-2 font-bold text-emerald-700"><ArrowRight className="h-4 w-4" /> العودة إلى المعرفة</Link><div className="mt-8 flex items-center gap-4"><div className="rounded-2xl bg-emerald-100 p-4 text-emerald-700"><MessageCircle /></div><div><h1 className="text-3xl font-black text-slate-900">استشارة تغذية طبيعية</h1><p className="mt-2 text-slate-600">شارك هدفك الغذائي وسيتواصل معك فريق قطوف الطبيعة.</p></div></div>{submitted ? <div className="mt-10 rounded-3xl bg-emerald-50 p-8 text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-600" /><h2 className="mt-4 text-2xl font-black text-emerald-900">تم استلام طلبك</h2><p className="mt-2 leading-7 text-emerald-800">سنراجع المعلومات ونتواصل معك. لا تُعد هذه الخدمة بديلًا عن الرعاية الطبية.</p></div> : <form onSubmit={onSubmit} className="mt-8 grid gap-5"><label className="grid gap-2 font-bold">الاسم<input name="contactName" required maxLength={120} className="rounded-xl border p-3 font-normal" /></label><label className="grid gap-2 font-bold">رقم التواصل<input name="contactPhone" inputMode="tel" className="rounded-xl border p-3 font-normal" /></label><label className="grid gap-2 font-bold">البريد الإلكتروني<input name="contactEmail" type="email" className="rounded-xl border p-3 font-normal" /></label><label className="grid gap-2 font-bold">ما هدفك من الاستشارة؟<textarea name="goal" required maxLength={1000} rows={4} className="rounded-xl border p-3 font-normal" /></label><label className="grid gap-2 font-bold">قيود أو تفضيلات غذائية<textarea name="dietaryRestrictions" maxLength={1000} rows={3} className="rounded-xl border p-3 font-normal" /></label><label className="grid gap-2 font-bold">الوقت المناسب للتواصل<input name="preferredContactTime" maxLength={100} className="rounded-xl border p-3 font-normal" /></label><label className="flex items-start gap-3 text-sm leading-6 text-slate-600"><input name="consent" type="checkbox" required className="mt-1" />أوافق على استخدام هذه البيانات للتواصل بخصوص الاستشارة، وأفهم أنها خدمة تثقيفية وليست تشخيصًا طبيًا.</label>{error && <p className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<button className="rounded-2xl bg-emerald-600 px-5 py-3 font-black text-white transition hover:bg-emerald-700">إرسال طلب الاستشارة</button></form>}</section></main>;
}
